### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by zedboi77** [KaspianDev/AntiPopup#14]
[05:09:15 WARN]: [com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: index: 3, length: 19 (expected: range(0, 3))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1270) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.toString(ByteBufOperatorModernImpl.java:215) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.toString(ByteBufHelper.java:63) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:379) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:55) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:174) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:104) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:94) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:39) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketReceive(InternalPacketListener.java:121) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:77) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:63) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:90) ~[AntiPopup-4.6.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:122) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:58:52 INFO]: [Vault] Checking for Updates ... 
[09:58:52 INFO]: [Vault] No new version available

**Comment by KaspianDev** [comment]
Don't post errors like that, use gist or hastebin.
Please also add reproduction steps to the issue.
For now I'll mark it as invalid

**Comment by shovelbug** [comment]
i have same issue i also dont know how to reproduce but it keeps happening every now and then and i think sometimes it affects players abilities to join the server.....as i am unable to give reproduction steps i doubt putting my log in a new issue will warrant anything except it being flagged as invalid too

**Comment by velnias75** [comment]
> i have same issue i also dont know how to reproduce but it keeps happening every now and then and i think sometimes it affects players abilities to join the server.....as i am unable to give reproduction steps i doubt putting my log in a new issue will warrant anything except it being flagged as invalid too

I have the same error too, also not reproduceable :_(

**Comment by KaspianDev** [comment]
> > i have same issue i also dont know how to reproduce but it keeps happening every now and then and i think sometimes it affects players abilities to join the server.....as i am unable to give reproduction steps i doubt putting my log in a new issue will warrant anything except it being flagged as invalid too
> 
> I have the same error too, also not reproduceable. :-(
> 
> `This server is running Paper version git-Paper-160 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 8db45c4)` `[00:04:25 INFO]: Plugins (23): AntiPopup, DiscordSRV, dynmap, EzHomes, Graves, Images, JoinMessage, LuckPerms, NoMobGriefing, PangaeaBlocks, PhatLoots, PinkBull, ProtocolLib, RainManNG, RHSignItem, SEC, ServerBackup, spark, TAB, TABWorldDate, ViewDistanceTweaks, VipSlot*, XItemsRemover`
> 
> https://gist.github.com/velnias75/ea8bd4ad5de0aac3fddbb43604bf9369

Can you create the issue on packetevents github page? I think it's related to it rather than my code.

**Comment by KaspianDev** [comment]
@zedboi77 @velnias75 

[> This <](https://github.com/KaspianDev/AntiPopup/releases/tag/2cd7dce) should have an option to suppress that warning, let me know if it works.

**Comment by MWHunter** [comment]
This error is harmless and is caused by a client sending an invalid handshaking message.  These logs are just usually ignored by the server.
