### ISSUE TITLE
IllegalStateException: PacketEvents failed to find a ByteToMessageDecoder

### ISSUE THREAD

**Issue by mibby** [KaspianDev/AntiPopup#16]
Purpur dev 1838 (Paper 1.19.2)
ProtocolLib dev 602
AntiPopup 4.6

This error occurs every time someone logs in.

```
[04:50:43] [Netty Epoll Server IO #2/WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder$$Lambda$12646/0x0000000803da2860.operationComplete()
java.lang.IllegalStateException: PacketEvents failed to find a ByteToMessageDecoder indexed 0 by its type in the net.minecraft.network.PacketDecoder class!
	at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(ReflectionObject.java:297) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(ReflectionObject.java:159) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.readObject(ReflectionObject.java:148) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.changeConnectionState(SpigotChannelInjector.java:219) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.manager.InternalPacketListener.lambda$onPacketSend$0(InternalPacketListener.java:77) ~[AntiPopup-4.6.jar:?]
	at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.lambda$write$0(PacketEventsEncoder.java:100) ~[AntiPopup-4.6.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:364) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:260) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:471) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:429) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:138) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib.jar:?]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:460) ~[?:?]
	at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:434) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Config
```
config-version: '9'

# Should we collect anonymous data about your server?
# false by default.
bstats: false

# Should we prevent messages from being reported?
# Leave as yes until you have a different plugin stripping those.
strip-signature: true

dont-send-header: true

# Do not touch this!
first-run: false
ask-bstats: false
```

**Comment by KaspianDev** [comment]
What version is the server on?

**Comment by KaspianDev** [comment]
> @KaspianDev Compiled & tested AntiPopup 5-RC3 as of commit [fd7f628](https://github.com/KaspianDev/AntiPopup/commit/fd7f628f91966359a9b00925d48206466006a60f)
> 
> Doing a deeper dive into locating the problem, it seems to be caused by using ViaVersion-DEV 754. https://ci.viaversion.com/job/ViaVersion-DEV/
> 
> More specifically, the breaking change seemingly comes from dev 741 ([ViaVersion/ViaVersion@24ef555](https://github.com/ViaVersion/ViaVersion/commit/24ef555eb02f02f40de4c84135f1ecb55a7b421f)). I'm not sure if the Via hook needs to be updated to bring compatibility back with the newer Via version or if something needs fixing in ViaVersion. Figured it's worth noting before ViaVersion dev commits are pushed into master for final 1.19.2 build / 1.19.3 release though.

Okay we will deal with this once via stable releases. Thanks for the info.

**Comment by MWHunter** [comment]
This should no longer be an issue
