### ISSUE TITLE
NoSuchElementException on shutdown

### ISSUE THREAD

**Issue by BlockyTheDev** [KaspianDev/AntiPopup#17]
```
[19:21:26 INFO]: [AntiPopup] Disabling AntiPopup v4.6
[19:21:26 ERROR]: Error occurred while disabling AntiPopup v4.6 (Is it up to date?)
java.util.NoSuchElementException: pe-connection-handler-antipopup
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninjectServerChannel(SpigotChannelInjector.java:188) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninject(SpigotChannelInjector.java:131) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.terminate(SpigotPacketEventsBuilder.java:236) ~[AntiPopup-4.6.jar:?]
        at com.github.kaspiandev.antipopup.AntiPopup.onDisable(AntiPopup.java:121) ~[AntiPopup-4.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:808) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:898) ~[paper-1.19.2.jar:git-Paper-300]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[paper-1.19.2.jar:git-Paper-300]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[paper-1.19.2.jar:git-Paper-300]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[paper-1.19.2.jar:git-Paper-300]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1486) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-300]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-300]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by KaspianDev** [comment]
I've noticed this happen when server turned off incorrectly (for example when something else crashed it). Generally shouldn't be dangerous.

**Comment by MWHunter** [comment]
This code no longer exists on latest packetevents.

**Comment by BlockyTheDev** [comment]
```java
[01:58:50 ERROR]: Error occurred while disabling AntiPopup v5.1 (Is it up to date?)
java.util.NoSuchElementException: pe-connection-handler-antipopup
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninjectServerChannel(SpigotChannelInjector.java:184) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.uninject(SpigotChannelInjector.java:127) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.terminate(SpigotPacketEventsBuilder.java:224) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.AntiPopup.onDisable(AntiPopup.java:143) ~[AntiPopup-5.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:943) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:808) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.close(MinecraftServer.java:898) ~[paper-1.19.2.jar:git-Paper-307]
        at org.spigotmc.RestartCommand.shutdownServer(RestartCommand.java:92) ~[paper-1.19.2.jar:git-Paper-307]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:61) ~[paper-1.19.2.jar:git-Paper-307]
        at org.spigotmc.RestartCommand.restart(RestartCommand.java:40) ~[paper-1.19.2.jar:git-Paper-307]
        at org.spigotmc.RestartCommand$1.run(RestartCommand.java:31) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1486) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

**Comment by BlockyTheDev** [comment]
@KaspianDev Not fixed by Upstream

**Comment by KaspianDev** [comment]
Please check latest github actions.

**Comment by BlockyTheDev** [comment]
Ohh I taught that the last commit was before the last update.
