### ISSUE TITLE
error hmm

### ISSUE THREAD

**Issue by dinobossytnew** [KaspianDev/AntiPopup#18]
software: purpur 1.19.2
log : https://mclo.gs/gBjgveZ
Plugins (67): AdvancedKits, AlonsoTags, AnimatedScoreboard, AntiPopup, BanItem, BankPlus, BetterBackpacks, BetterRevive, BungeeGuard, Chunky, Citizens, CoreProtect, CraftingStore, CustomCrops, CustomDrops, CustomFishing, DecentHolograms, DeluxeCombat, DeluxeMenus, Dungeons, EasyCommandBlocker, Essentials, EssentialsProtect, EssentialsSpawn, ExecutableItems, FunServ-AntiWither*, Graves, HeadDatabase, Interactions, InventorySaver, ItemsAdder, LoneLibs, LPC, LuckPerms, MCPets, MMOItems, ModelEngine, Multiverse-Core, MythicCrucible, MythicLib, MythicMobs, MythicMobsGUI, NBTAPI, nLogin, OreRegenerator, PlaceholderAPI, ProtectionStones, ProtocolLib, PyroLib, PyroSpawners, RandomTP, Resources, SCore, Shopkeepers, SimpleRename, SkinsRestorer, sleep-most, spark, StorageMechanics, TAB, TerraformGenerator, UltimateClans, Vault, VoidGen, WolfyUtilities, WorldEdit, WorldGuard

All the plugins were purchased I notice because I am not leak :D

**Comment by nhanledev** [comment]
I have the same problem in latest dev build
```
[10:09:50 WARN]: [io.netty.util.concurrent.DefaultPromise] An exception was thrown by com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder$$Lambda$11829/0x00000008035344c0.operationComplete()
java.lang.IllegalStateException: PacketEvents failed to find a ByteToMessageDecoder indexed 0 by its type in the net.minecraft.network.PacketDecoder class!
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.getField(ReflectionObject.java:297) ~[AntiPopup-5-RC5.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.read(ReflectionObject.java:159) ~[AntiPopup-5-RC5.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.reflection.ReflectionObject.readObject(ReflectionObject.java:148) ~[AntiPopup-5-RC5.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.SpigotChannelInjector.changeConnectionState(SpigotChannelInjector.java:219) ~[AntiPopup-5-RC5.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.manager.InternalPacketListener.lambda$onPacketSend$0(InternalPacketListener.java:77) ~[AntiPopup-5-RC5.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.lambda$write$0(PacketEventsEncoder.java:100) ~[AntiPopup-5-RC5.jar:?]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollChannel.doWriteBytes(AbstractEpollChannel.java:364) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytes(AbstractEpollStreamChannel.java:260) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteSingle(AbstractEpollStreamChannel.java:471) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:429) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.flushNow(FlushConsolidationHandler.java:204) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.flush(FlushConsolidationHandler.java:138) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-b605.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-b605.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:460) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:434) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib-b605.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
```

**Comment by dinobossytnew** [comment]
> Duplicate of #16?

You don't think it's a purpur thing or some new system?

**Comment by nhanledev** [comment]
this was fix in ver5 :) tysm
