### ISSUE TITLE
IndexOutOfBoundsException on player connect

### ISSUE THREAD

**Issue by SlimeDog** [KaspianDev/AntiPopup#23]
Paper 1.19.3-316
AntiPopup 5.1

On player connect
```
[10:06:07 WARN]: [com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: readerIndex(6596) + length(1) exceeds writerIndex(6596): PooledUnsafeDirectByteBuf(ridx: 6596, widx: 6596, cap: 8192)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.82.Final.jar:4.1.82.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.readByte(ByteBufOperatorModernImpl.java:74) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.readByte(ByteBufHelper.java:67) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readByte(PacketWrapper.java:222) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readBoolean(PacketWrapper.java:234) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerServerData.read(WrapperPlayServerServerData.java:58) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:179) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:124) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:114) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerServerData.<init>(WrapperPlayServerServerData.java:37) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.listeners.PacketEventsListener.onPacketSend(PacketEventsListener.java:32) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:43) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:57) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:41) ~[AntiPopup-5.1.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:77) ~[AntiPopup-5.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227) ~[ProtocolLib-5.0.0-b606.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233) ~[ProtocolLib-5.0.0-b606.jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48) ~[ProtocolLib-5.0.0-b606.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by KaspianDev** [comment]
1.19.3 isn't supported yet. Waiting for dependency to update.

**Comment by SlimeDog** [comment]
What is the dependency, please?

**Comment by KaspianDev** [comment]
> What is the dependency, please?

PacketEvents, they are working on it.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
PacketEvents appears to support 1.19.3: https://github.com/retrooper/packetevents/releases

**Comment by KaspianDev** [comment]
> PacketEvents appears to support 1.19.3: https://github.com/retrooper/packetevents/releases

There are problems with my current methods on 1.19.3 server.

**Comment by SlimeDog** [comment]
> There are problems with my current methods on 1.19.3 server.

OK. I've deleted it for now.

**Comment by KaspianDev** [comment]
Check out latest pre release -> https://github.com/KaspianDev/AntiPopup/releases/tag/b364a53

**Comment by RomLecat** [comment]
Just tested it on Paper 1.19.3-316, works perfectly. Thanks!

**Comment by SlimeDog** [comment]
Also looks ok on Spigot 1.19.3-3630, with the following configuration (`setup-mode: true` at start-up):
```
config-version: '26'
bstats: true
filter-not-secure: true
strip-signature: true
dont-send-header: true
auto-setup: false
mode: BUKKIT
first-run: false
ask-bstats: false
setup-mode: false
```

**Comment by KaspianDev** [comment]
> Also looks ok on Spigot 1.19.3-3630, with the following configuration (`setup-mode: true` at start-up):
> 
> ```
> config-version: '26'
> bstats: true
> filter-not-secure: true
> strip-signature: true
> dont-send-header: true
> auto-setup: false
> mode: BUKKIT
> first-run: false
> ask-bstats: false
> setup-mode: false
> ```

Yup it should be like this. It detects compatible mode on first startup of 5.2 now.

Due to problems with my hard drive, packet mode for 1.19.3 will be delayed by at least 4 days.

**Comment by SlimeDog** [comment]
What is the difference between PACKET mode and BUKKIT mode?

**Comment by KaspianDev** [comment]
PACKET mode uses packets to remove the signature, while BUKKIT mode uses bukkit event. While the first one is more compatible, there are issues with updating it currently, and BUKKIT mode additionally brings back clickable URLs in player messages.
