### ISSUE TITLE
RuntimeException on player chat message

### ISSUE THREAD

**Issue by paul-eff** [KaspianDev/AntiPopup#24]
Paper Version: 1.19.3-327
AntiPopup Version: 5.1

Reproducable: Yes
When: On player chat message

I am aware that you are waiting for the library to finally update as already mentioned in #23 [here](https://github.com/KaspianDev/AntiPopup/issues/23#issuecomment-1345358264).
Leaving this here for good measure.

<pre><code>
[01:54:09 WARN]: [com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.RuntimeException: The received encoded string buffer length is longer than maximum allowed (1165507 > 1048576)
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:380) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponentJSON(PacketWrapper.java:395) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readComponent(PacketWrapper.java:424) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readOptional(PacketWrapper.java:957) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.protocol.chat.message.reader.impl.ChatMessageProcessor_v1_19_1.readChatMessage(ChatMessageProcessor_v1_19_1.java:42) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChatMessage.read(WrapperPlayServerChatMessage.java:59) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:179) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:124) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:114) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerChatMessage.<init>(WrapperPlayServerChatMessage.java:49) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.listeners.PacketEventsListener.onPacketSend(PacketEventsListener.java:37) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:48) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:43) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:57) ~[AntiPopup-5.1.jar:?]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:41) ~[AntiPopup-5.1.jar:?]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at com.github.kaspiandev.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:77) ~[AntiPopup-5.1.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) ~[netty-codec-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:459) ~[?:?]
        at net.minecraft.network.Connection.lambda$sendPacket$11(Connection.java:433) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
</code></pre>

**Comment by KaspianDev** [comment]
Duplicate?
(already being worked on)
