### ISSUE TITLE
[BUG] 1.19.2 Errors

### ISSUE THREAD

**Issue by assada** [KaspianDev/AntiPopup#52]
### Describe the bug

```
! [Fri 23:04:06 WARN  com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "java.util.function.Function.apply(Object)" because "com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.adventure.AdventureReflectionUtil.SHOW_ENTITY_SERIALIZER_CREATE" is null
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.adventure.SerializerFactory.create(SerializerFactory.java:61)
    at com.google.gson.Gson.getAdapter(Gson.java:489)
    at com.google.gson.Gson.fromJson(Gson.java:962)
    at com.google.gson.Gson.fromJson(Gson.java:1034)
    at com.google.gson.Gson.fromJson(Gson.java:1006)
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.adventure.HoverSerializer.deserializeShowEntity(HoverSerializer.java:95)
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.adventure.StyleSerializerExtended.read(StyleSerializerExtended.java:157)
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.util.adventure.StyleSerializerExtended.read(StyleSerializerExtended.java:39)
    at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    at com.google.gson.Gson.fromJson(Gson.java:963)
    at com.google.gson.Gson.fromJson(Gson.java:1034)
    at com.google.gson.Gson.fromJson(Gson.java:1006)
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:214)
    at AntiPopup-5.7.jar//com.github.kaspiandev.antipopup.libs.net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.read(ComponentSerializerImpl.java:56)
    at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
    at com.google.gson.Gson.fromJson(Gson.java:963)
    at com.google.gson.Gson.from
```

### To Reproduce

Just run server

### Operating System

Ubuntu

### Server Software

Paper 1.19.2

### Server Version

1.19.2

### Proxy Type

None

### Plugin List

```bash
Spartan, AntiPopup
```

### Server logs

-

**Comment by KaspianDev** [comment]
send me your config

**Comment by assada** [comment]
```yaml
config-version: '29'

# Should we collect anonymous data about your server?
# false by default.
bstats: false

# Should we remove [Not Secure] from /say?
# There is a very small chance of catching something
# that should not be caught. If that happens report the
# incident to Github issues of AntiPopup.
filter-not-secure: true

# Should we prevent messages from being reported?
# Leave as yes until you have a different plugin stripping those.
strip-signature: true

dont-send-header: true

# Should setup be ran on first start?
# Useful for all kinds of setups or server hosts.
auto-setup: false

# NMS - Only for 1.19.3 and 1.19.4.
# PACKET - Only up to 1.19.2.
mode: PACKET

# Readd clickable URLs in messages.
# Could cause incompabilities!
clickable-urls: false

# Do not touch this!
first-run: false
ask-bstats: false
setup-mode: false

```

**Comment by KaspianDev** [comment]
send me your entire server log because i cant reproduce with similar setup
