### ISSUE TITLE
[BUG] 1.20.1 not supported

### ISSUE THREAD

**Issue by cosmohdx** [KaspianDev/AntiPopup#58]
### Describe the bug

```2023-06-16T15:54:41.884286578Z 17:54:41.884  INFO - [Server thread] AntiPopup                 : Enabling AntiPopup v6
2023-06-16T15:54:42.076924305Z 17:54:42.076  INFO - [Server thread] AntiPopup                 : Config enabled.
2023-06-16T15:54:42.081528543Z 17:54:42.081  INFO - [Server thread] AntiPopup                 : Initiated PacketEvents.
2023-06-16T15:54:42.082185222Z 17:54:42.081 ERROR - [Server thread] AntiPopup                 : No supported server version found! Exiting.
2023-06-16T15:54:42.082818045Z 17:54:42.082  INFO - [Server thread] AntiPopup                 : Disabling AntiPopup v6
2023-06-16T15:54:42.084150835Z 17:54:42.083  INFO - [Server thread] AntiPopup                 : Disabled PacketEvents.```

Version Paper 1.20.1

### To Reproduce

Start with current Paper version

### Expected behavior

_No response_

### Operating System

Linux

### Server Software

Paper 1.20.1 (22)

### Server Version

1.19

### Proxy Type

None

### Plugin List

```bash
n/a
```

### Server logs

see at report

**Comment by hohoaisan** [comment]
```
[23:27:58 ERROR]: Error occurred while enabling AntiPopup v6 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
        at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
        at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
        at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:195) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.github.kaspiandev.antipopup.AntiPopup.onEnable(AntiPopup.java:124) ~[AntiPopup-6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-29]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:566) ~[paper-1.20.1.jar:git-Paper-29]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.20.1.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-29]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-29]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-29]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

same issue on paper-1.20.1-29

**Comment by KaspianDev** [comment]
Fixed in newest release
