### ISSUE TITLE
[BUG] Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION

### ISSUE THREAD

**Issue by DexterSK** [KaspianDev/AntiPopup#71]
### Describe the bug

```
[18:14:54 WARN]: io.netty.handler.codec.EncoderException: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[18:14:54 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:54 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:54 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[18:14:54 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[18:14:54 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[18:14:54 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[18:14:54 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:227)
[18:14:54 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.writeAndFlush(NettyChannelProxy.java:233)
[18:14:54 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[18:14:54 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[18:14:54 WARN]:        at ProtocolLib.jar//com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:48)
[18:14:54 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[18:14:54 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[18:14:54 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[18:14:54 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[18:14:54 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[18:14:54 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[18:14:54 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[18:14:54 WARN]: Caused by: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:55)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[18:14:54 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[18:14:54 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[18:14:54 WARN]:        ... 34 more
```

### To Reproduce

im not sure, happens when someone login

### Operating System

Linux

### Server Software

git-Purpur-2083 (MC: 1.20.2)*

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
x
```

### Server logs

https://mclo.gs/WyQLdFx

**Comment by KaspianDev** [comment]
I need full server log. Also first please try Paper or Spigot.

**Comment by Foxikle** [comment]
I am also having this issue with paper

#### Paper Version: git-paper-260
#### Proxy Velocity 3.2.0-snapshot
Expected Behavour:
```
Not throwing an error and kicking player
```

Steps to reproduce:
```
Log into the proxy
get kicked
```

```
Starting org.bukkit.craftbukkit.Main
System Info: Java 20 (OpenJDK 64-Bit Server VM 20.0.2+9) Host: Linux 5.15.0-87-generic (amd64)
Loading libraries, please wait...
[15:06:42 INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[15:06:45 INFO]: Loaded 7 recipes
[15:06:46 INFO]: Starting minecraft server version 1.20.2
[15:06:46 INFO]: Loading properties
[15:06:46 INFO]: This server is running Paper version git-Paper-260 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 1865625)
[15:06:47 INFO]: Server Ping Player Sample Count: 12
[15:06:47 INFO]: Using 4 threads for Netty based IO
[15:06:47 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[15:06:48 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[15:06:48 INFO]: Default game type: SURVIVAL
[15:06:48 INFO]: Generating keypair
[15:06:49 INFO]: Starting Minecraft server on 0.0.0.0:8237
[15:06:49 INFO]: Using epoll channel type
[15:06:49 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[15:06:49 INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[15:06:49 INFO]: [SpigotLibraryLoader] [AntiPopup] Loading 1 libraries... please wait
[15:06:49 INFO]: [SpigotLibraryLoader] [AntiPopup] Loaded library /home/container/libraries/dev/dejvokep/boosted-yaml-spigot/1.3/boosted-yaml-spigot-1.3.jar
[15:06:49 INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.3
[15:06:49 INFO]: [FastAsyncWorldEdit] Loading server plugin FastAsyncWorldEdit v2.8.2-SNAPSHOT-598;1f8976b
[15:06:51 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@7ff5b4d8]
[15:06:51 INFO]: [DiscordWebhookPaper] Loading server plugin DiscordWebhookPaper v0.01-alpha1
[15:06:51 INFO]: [FoxRank] Loading server plugin FoxRank v2.0.0-beta5
[15:06:51 INFO]: [AntiPopup] Loading server plugin AntiPopup v7.1
[15:06:52 INFO]: [AntiPopup] Loaded PacketEvents.
[15:06:52 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:06:52 INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v2.8.2-SNAPSHOT-598;1f8976b
[15:06:52 INFO]: [com.fastasyncworldedit.core.Fawe] LZ4 Compression Binding loaded successfully
[15:06:52 INFO]: [com.fastasyncworldedit.core.Fawe] ZSTD Compression Binding loaded successfully
[15:06:52 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[15:06:53 INFO]: WEPIF: Using the Bukkit Permissions API.
[15:06:53 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_20_R2.PaperweightFaweAdapter as the Bukkit adapter
[15:06:54 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[15:06:54 WARN]: The server will make no attempt to authenticate usernames. Beware.
[15:06:54 WARN]: Whilst this makes it possible to use Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[15:06:54 WARN]: Please see https://docs.papermc.io/velocity/security for further information.
[15:06:54 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[15:06:54 INFO]: Preparing level "world"
[15:06:55 WARN]: [com.fastasyncworldedit.core.util.UpdateNotification] An update for FastAsyncWorldEdit is available. You are 8 build(s) out of date.
You are running build 598, the latest version is build 606.
Update at https://www.spigotmc.org/resources/13932/
[15:06:55 INFO]: Preparing start region for dimension minecraft:overworld
[15:06:55 INFO]: Time elapsed: 398 ms
[15:06:55 INFO]: Preparing start region for dimension minecraft:the_nether
[15:06:55 INFO]: Time elapsed: 194 ms
[15:06:55 INFO]: Preparing start region for dimension minecraft:the_end
[15:06:56 INFO]: Time elapsed: 181 ms
[15:06:56 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.3
[15:06:56 INFO]: [PlaceholderAPI] Fetching available expansion information...
[15:06:56 INFO]: [DiscordWebhookPaper] Enabling DiscordWebhookPaper v0.01-alpha1
[15:06:56 WARN]: [DiscordWebhookPaper] Could not save config.yml to plugins/DiscordWebhookPaper/config.yml because config.yml already exists.
[15:06:56 INFO]: [FoxRank] Enabling FoxRank v2.0.0-beta5
[15:06:57 INFO]: [FoxRank] Database connected.
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: ban [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: line [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: log [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: mute [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: nickname [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: playerrank [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: server [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: syntax [v1.9.6]
[15:07:04 INFO]: [PlaceholderAPI] Successfully registered expansion: target [v1.9.6]
[15:07:04 INFO]: [AntiPopup] Enabling AntiPopup v7.1
[15:07:04 INFO]: [AntiPopup] Config enabled.
[15:07:04 INFO]: [AntiPopup] Initiated PacketEvents.
[15:07:04 INFO]: [AntiPopup] Hooked on 1.20.2
[15:07:04 INFO]: [AntiPopup] Commands registered.
[15:07:04 INFO]: [AntiPopup] Logger filter enabled.
[15:07:04 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[15:07:04 INFO]: 0 placeholder hook(s) registered!
[15:07:04 INFO]: Running delayed init tasks
[15:07:04 INFO]: Done (18.579s)! For help, type "help"
dash@mc-servers.tech~ MCST-Server marked as running...
[15:07:04 INFO]: Timings Reset
[15:07:05 INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.11.5) is available at:
[15:07:05 INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
[15:15:32 INFO]: UUID of player Foxikle is 7f3208cb-05b7-4b35-819c-a58438158fbc
[15:15:33 INFO]: Foxikle[/47.14.68.191:49964] logged in with entity id 43 at ([world]-12.537163507128449, 136.86439390647385, 4.688939632017946)
[15:16:05 INFO]: UUID of player Hyper7285 is 92d4cbb8-9ba0-4053-ab6f-509cf18a1fdb
[15:16:20 WARN]: io.netty.handler.codec.EncoderException: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[15:16:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:16:20 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[15:16:20 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[15:16:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:16:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:16:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[15:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:16:20 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:16:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:16:20 WARN]: Caused by: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:55)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[15:16:20 WARN]:        ... 27 more
[15:16:20 WARN]: io.netty.handler.codec.EncoderException: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984)
[15:16:20 WARN]:        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
[15:16:20 WARN]:        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
[15:16:20 WARN]:        at net.minecraft.network.NetworkManager.c(NetworkManager.java:448)
[15:16:20 WARN]:        at net.minecraft.network.NetworkManager.lambda$sendPacket$10(NetworkManager.java:433)
[15:16:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[15:16:20 WARN]:        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[15:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[15:16:20 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
[15:16:20 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:16:20 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:16:20 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1623)
[15:16:20 WARN]: Caused by: com.github.kaspiandev.antipopup.libs.packetevents.exception.PacketProcessException: Failed to map the Packet ID 36 to a PacketType constant. Bound: CLIENT, Connection state: CONFIGURATION, Server version: 1.20.2
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.ProtocolPacketEvent.<init>(ProtocolPacketEvent.java:88)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.PacketSendEvent.<init>(PacketSendEvent.java:37)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.event.simple.PacketPlaySendEvent.<init>(PacketPlaySendEvent.java:33)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.EventCreationUtil.createSendEvent(EventCreationUtil.java:55)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:42)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67)
[15:16:20 WARN]:        at AntiPopup-7.1.jar//com.github.kaspiandev.antipopup.libs.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46)
[15:16:20 WARN]:        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
[15:16:20 WARN]:        ... 27 more
[15:16:35 INFO]: com.mojang.authlib.GameProfile@711d02ec[id=92d4cbb8-9ba0-4053-ab6f-509cf18a1fdb,name=Hyper7285,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTY5OTcxNTc1MjQ0MSwKICAicHJvZmlsZUlkIiA6ICI5MmQ0Y2JiODliYTA0MDUzYWI2ZjUwOWNmMThhMWZkYiIsCiAgInByb2ZpbGVOYW1lIiA6ICJIeXBlcjcyODUiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjJkYjA4YmVhMjczYTU5YWM3MWY1YjA0M2E3MzExMGNhNTA5ZmFhN2EwNzAzNGI2MzNkZDgxOTFjYmE4NTNmZCIKICAgIH0KICB9Cn0=, signature=jYuhT+x0WPpkAC/w43R0hG86TRmYUQugZq7kR/ks66pirN1zVTGCBHq6/gYkgNaGsQJcw7GibvlmKkkwsptd89e2INQ/0K3j32vSGZNOOC+6a2DCZoX8H4F+wvrSrPPlQhSMPZUM8089enFKXVZGrXHNAOjjF1osLpK+gpRdArLxIhGRMHpazKujGUFatlmv3ME7iAJ3wrBRl+kzkLokCHnUAnLTIHzvVXQQU9pO8Q7HxXzyTMUVbP+MSSVUaj6ByPi59VA6YJiMktmSL4VQ9stfg063E7WRYYX98IMnXHQqbbpvZUmfkmZAD5qMdQ9vXVcZaqVMH+WGBAzfxuk8XwysY9gy4EVS/lRu6ZE5/e58DOlL3q9YDqGF2eibz8xG7DcFtpo2kaFY7rgiuSLB1LzvYq1+t3ps7FgQmGCcSu9Tn0aP+anMaPFXXOfC/hCdaN79rRYrbPCi5Fdo/BsVNu91xyMlFkeHOTvSvD5ct0Pju5B/1TlgvX3GKmDkv31QEQ9Ss27UJKuTTHz/L0vTaZ+rxCWiDNBL3znaN/ndOElsosa6NZdhxQc4T0ju3l5mQKeDoBLTI/oyXILjOztp+eqrnmTD/m1qiA7ESt/GpSoCthhS1qeXA8QIQ6XuEfXhy4LnO6HuaS+l+X62GV0K473LmObXwD4kp5rfJAjsm8o=]]}] lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer

```

**Comment by KaspianDev** [comment]
dm me on discord
