### ISSUE TITLE
PacketEvents caught an unhandled exception while calling your listener.

### ISSUE THREAD

**Issue by SuggarHidden** [KaspianDev/AntiPopup#8]
**Server: git-Paper-101
Version: 1.19.1**        

`[WARN]: [screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.IndexOutOfBoundsException: index: 3, length: 19 (expected: range(0, 3))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1270) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1246) ~[netty-buffer-4.1.77.Final.jar:4.1.77.Final]
        at screw.microsoft.antipopup.libs.io.github.retrooper.packetevents.netty.buffer.ByteBufOperatorModernImpl.toString(ByteBufOperatorModernImpl.java:215) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.netty.buffer.ByteBufHelper.toString(ByteBufHelper.java:63) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readString(PacketWrapper.java:378) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.read(WrapperHandshakingClientHandshake.java:55) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.readEvent(PacketWrapper.java:173) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:103) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.PacketWrapper.<init>(PacketWrapper.java:93) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.wrapper.handshaking.client.WrapperHandshakingClientHandshake.<init>(WrapperHandshakingClientHandshake.java:39) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.manager.InternalPacketListener.onPacketReceive(InternalPacketListener.java:121) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.event.PacketReceiveEvent.call(PacketReceiveEvent.java:45) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:51) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleServerBoundPacket(PacketEventsImplHelper.java:77) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.read(PacketEventsDecoder.java:63) ~[AntiPopup.jar:?]
        at screw.microsoft.antipopup.libs.io.github.retrooper.packetevents.injector.handlers.PacketEventsDecoder.decode(PacketEventsDecoder.java:90) ~[AntiPopup.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at net.minecraft.server.network.LegacyQueryHandler.channelRead(LegacyQueryHandler.java:122) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[netty-transport-classes-epoll-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by KaspianDev** [comment]
@SuggarHidden make sure you are on latest AntiPopup

**Comment by SuggarHidden** [comment]
I am using AntiPopup v3.1, could it be because of a proxy command? I only got the error once I was using paper, now I am using pupur.

**Comment by KaspianDev** [comment]
> I am using AntiPopup v3.1, could it be because of a proxy command? I only got the error once I was using paper, now I am using pupur.

Join my discord, it will be much faster to help you out.

**Comment by paul-eff** [comment]
Was a solution found yet or is a patch on it's way? :)
I have the exact same issues.

StackTrace: https://pastebin.com/Ak7i8KZw

**Comment by SuggarHidden** [comment]
I didn't find any solution, and due to lack of time, I preferred to change plugin.

**Comment by KaspianDev** [comment]
> Was a solution found yet or is a patch on it's way? :) I have the exact same issues.
> 
> Server: Ubuntu 20.04.4 LTS Java: openjdk version "17.0.4" Paper: git-Paper-113 (MC: 1.19.2)
> 
> Stack trace: https://pastebin.com/Ak7i8KZw

Under proxy?
Also send plugin list

**Comment by KaspianDev** [comment]
https://github.com/KaspianDev/AntiPopup/actions/runs/2851827834"
let me know if it fixes
@SuggarHidden

**Comment by paul-eff** [comment]
> > Was a solution found yet or is a patch on it's way? :) I have the exact same issues.
> 
> > 
> 
> > Server: Ubuntu 20.04.4 LTS Java: openjdk version "17.0.4" Paper: git-Paper-113 (MC: 1.19.2)
> 
> > 
> 
> > Stack trace: https://pastebin.com/Ak7i8KZw
> 
> 
> 
> Under proxy?
> 
> Also send plugin list

Nope, no proxy.

Plugin list (recent versions): WorldEdit, Dynmap, DriveBackupV2 (is old haven't had time to find a replacement), AntiPopup

**Comment by KaspianDev** [comment]
> > > Was a solution found yet or is a patch on it's way? :) I have the exact same issues.
> > 
> > 
> > > 
> > 
> > 
> > > Server: Ubuntu 20.04.4 LTS Java: openjdk version "17.0.4" Paper: git-Paper-113 (MC: 1.19.2)
> > 
> > 
> > > 
> > 
> > 
> > > Stack trace: https://pastebin.com/Ak7i8KZw
> > 
> > 
> > Under proxy?
> > Also send plugin list
> 
> Nope, no proxy.
> 
> Plugin list (recent versions): WorldEdit, Dynmap, DriveBackupV2 (is old haven't had time to find a replacement), AntiPopup
> 
> I updated to git-Paper-125 (MC: 1.19.2) recently. Haven't seen the error since. Also there was no kicking players, this error just popped up in my terminal whilst no one was on the server and I was just doing a check if everything is doing fine.

Paper recently had a fix regarding kicking, perhaps it's related

**Comment by KaspianDev** [comment]
Without knowing when exactly error pops up I can't do much. Something must trigger it

**Comment by KaspianDev** [comment]
People on discord told me latest commit fixes the issue

https://github.com/KaspianDev/AntiPopup/actions/runs/2851827834
Get it there and reopen if that still happens.
