### ISSUE TITLE
[BUG] Plugin stop working under Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [KaspianDev/AntiPopup#80]
### Describe the bug

got error from antipopup

### To Reproduce

1.use this version for papermc(https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/)
2.try to running the plugin

### Operating System

Windows

### Server Software

git-Paper-"84a586f" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 84a586f on plugin-remapping)

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
[20:14:37 INFO]: Server Plugins (55):
[20:14:37 INFO]: Paper Plugins:
[20:14:37 INFO]:  - HuskSync, MarriageMaster
[20:14:37 INFO]: Bukkit Plugins:
[20:14:37 INFO]:  - AntiEndermanMushroom, AntiPopup, BarbatosStoryBook, BetterLogStrip, BetterRTP, BlockLocker, BungeeTabListPlus, ChunkHeat, Chunky, Citizens
[20:14:37 INFO]:  CMI, CMILib, CodFrame, CoreProtect, CoreProtectTNT, CrateReloaded, DiscordSRV, FastMinecart, GSit, InteractiveChat
[20:14:37 INFO]:  InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, *IronElevators, Jobs, *KeepItems, LiteBans, Lootin, LuckPerms, Multiverse-Core, NBTAPI
[20:14:37 INFO]:  PhantomSMP, PlaceholderAPI, PlugManX, PremiumVanish, ProtocolLib, PvPManager, qssuite-limited, QuickShop-Hikari, Residence, Shopkeepers
[20:14:37 INFO]:  ShopkeepersStandardization, spark, TrChat, TreeAssist, UserPrefix, Vault, ViewDistanceTweaks, VillagerTradeLimiter, WorldBorder, WorldEdit
[20:14:37 INFO]:  WorldEditSUI, WorldGuard, XConomy
```
```


### Server logs

https://paste.helpch.at/ulapakujuc.css

**Comment by YuanYuanOwO** [comment]
```
[20:08:00 ERROR]: Error occurred while enabling AntiPopup v7.3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.github.kaspiandev.antipopup.libs.packetevents.util.SpigotReflectionUtil
        at com.github.kaspiandev.antipopup.libs.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103) ~[AntiPopup-7.3.jar:?]
        at com.github.kaspiandev.antipopup.libs.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.init(SpigotPacketEventsBuilder.java:136) ~[AntiPopup-7.3.jar:?]
        at com.github.kaspiandev.antipopup.AntiPopup.onEnable(AntiPopup.java:101) ~[AntiPopup-7.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3 [in thread "Server thread"]
        at com.github.kaspiandev.antipopup.libs.packetevents.util.SpigotReflectionUtil.<clinit>(SpigotReflectionUtil.java:54) ~[AntiPopup-7.3.jar:?]
        at com.github.kaspiandev.antipopup.libs.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:103) ~[AntiPopup-7.3.jar:?]
        at com.github.kaspiandev.antipopup.AntiPopup.onLoad(AntiPopup.java:54) ~[AntiPopup-7.3.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        ... 3 more
```

**Comment by KaspianDev** [comment]
Why does paper have to always break stuff

**Comment by YuanYuanOwO** [comment]
> Why does paper have to always break stuff without any warning
> 
> For now I guess don't use that paper version

https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/  
check here  
This may be as soon as 1.20.5  
so i think it's not well at all....
