### ISSUE TITLE
[BUG] Could not pass event PlayerJoinEvent to AntiPopup v8.1

### ISSUE THREAD

**Issue by ZARAEM** [KaspianDev/AntiPopup#91]
### Describe the bug

[22:41:13 WARN]: [com.github.kaspiandev.antipopup.libs.packetevents.PacketEventsAPI] No data was sent for dimension Compound{{name=String(minecraft:overworld), id=Int(0)}} to ZARAEM
[22:41:13 ERROR]: Could not pass event PlayerJoinEvent to AntiPopup v8.1
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_20_R4/entity/CraftPlayer
        at AntiPopup-8.1.jar/com.github.kaspiandev.antipopup.nms.v1_20_6.PlayerInjector_v1_20_6.inject(PlayerInjector_v1_20_6.java:57) ~[AntiPopup-8.1.jar:?]
        at AntiPopup-8.1.jar/com.github.kaspiandev.antipopup.spigot.nms.PlayerListener.onJoin(PlayerListener.java:19) ~[AntiPopup-8.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor113.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-2-b4b8208]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-2-b4b8208]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-2-b4b8208]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-2-b4b8208]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-2-b4b8208]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_20_R4.entity.CraftPlayer
        ... 28 more

Everytime a player joins, this error is printed to console.

### To Reproduce

Start server

### Operating System

Debian 12

### Server Software

PaperMC 1.21 Experimental

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, DiscordIntegration, *DynamicSlots, Essentials, EssentialsChat, EssentialsDiscord, EssentialsGeoIP, GSit, InteractiveChat, LuckPerms, Ping-Wheel-Plugin, Pl3xMap, PlaceholderAPI, PlasmoVoice, ProtocolLib, RHLeafDecay, ServerBackup, spark, TAB
```

### Server logs

https://mclo.gs/4O2SCGG

**Comment by KaspianDev** [comment]
AntiPopup doesn't support 1.21 yet #92
