### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jhqwqmc** [KaspianDev/AntiPopup#95]
### Describe the bug

Error message when starting in velocity

### To Reproduce

Start the proxy server

### Operating System

Windows Server 2022

### Server Software

Velocity 3.3.0-SNAPSHOT (git-aa4e8780-b401)

### Server Version

Not Listed

### Proxy Type

Velocity

### Plugin List

```bash
antipopup, limboapi, limboreconnect, luckperms, minimotd-velocity, nantibot, nlogin, packetevents, pl-hide-pro, triton, velocity-tools
```

### Server logs

https://paste.fastmirror.net/?9221b7f0c424727e#7VAZbuzgXgeBxqdhmyHY6LDi3MW4piGrVHr4eyUExFzf

**Comment by jhqwqmc** [comment]
The problem still exists. I have updated the latest velocity and antipopup 9.1
```log
[01:09:42 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[01:09:42 ERROR]: Couldn't pass ProxyInitializeEvent to antipopup 9.1
java.lang.NoSuchMethodError: 'com.github.kaspiandev.antipopup.libs.packetevents.bstats.Metrics com.github.kaspiandev.antipopup.libs.packetevents.bstats.Metrics.createInstance(java.lang.Object, com.velocitypowered.api.proxy.ProxyServer, org.slf4j.Logger, java.nio.file.Path, int)'
        at com.github.kaspiandev.antipopup.libs.packetevents.velocity.factory.VelocityPacketEventsBuilder$1.init(VelocityPacketEventsBuilder.java:180) ~[?:?]
        at com.github.kaspiandev.antipopup.velocity.AntiPopup.onProxyInitialization(AntiPopup.java:49) ~[?:?]
        at com.github.kaspiandev.antipopup.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-406.jar:3.3.0-SNAPSHOT (git-e0f74a84-b406)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-406.jar:3.3.0-SNAPSHOT (git-e0f74a84-b406)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-406.jar:3.3.0-SNAPSHOT (git-e0f74a84-b406)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by KaspianDev** [comment]
@jhqwqmc @BAD7777 

https://polymart.org/resource/antipopup-pro.4921/updates?update=47367
or github release
