### ISSUE TITLE
[BUG] 1.18.2 PurPur "version doesn't support it" & broken ViaVersion

### ISSUE THREAD

**Issue by TomLewis** [KaspianDev/AntiPopup#96]
### Describe the bug

[10:31:18] [Server thread/INFO]: [AntiPopup] Enabling AntiPopup v9
[10:31:18] [Server thread/INFO]: [AntiPopup] Config enabled.
[10:31:18] [Server thread/INFO]: [AntiPopup] Loaded a hook for ViaVersion.
[10:31:18] [Server thread/INFO]: [AntiPopup] Registered a modifier targeted for versions older than 1.20.5.
[10:31:18] [Server thread/INFO]: [AntiPopup] Initiated PacketEvents.
[10:31:18] [Server thread/ERROR]: [AntiPopup] Blocking chat reports was enabled but your server
[10:31:18] [Server thread/ERROR]: [AntiPopup] version doesn't support it. Exiting.
[10:31:18] [Server thread/ERROR]: Error occurred while enabling AntiPopup v9 (Is it up to date?)
java.lang.IllegalStateException: Blocking chat reports was enabled but your server version isn't supported!
	at com.github.kaspiandev.antipopup.spigot.AntiPopup.onEnable(AntiPopup.java:115) ~[AntiPopup-9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[10:31:18] [Server thread/INFO]: [AntiPopup] Disabling AntiPopup v9
[10:31:18] [Server thread/INFO]: [AntiPopup] Disabled PacketEvents.

### To Reproduce

Use PurPur 1.18.2 with ViaVersion, install this plugin.

### Expected behavior

To work.

### Operating System

Debian 10

### Server Software

PurPur 1.18.2

### Server Version

1.19

### Proxy Type

None

### Plugin List

```bash
ViaVersion
```

### Server logs

no

**Comment by KaspianDev** [comment]
Chat reporting doesn't exist on 1.18.2. Disable `block-chat-reports` in config if you wanna block the popup.

**Comment by TomLewis** [comment]
Yeah I just want to block the popup from all the 1.19+ clients connecting with viaversion

**Comment by KaspianDev** [comment]
> Yeah I just want to block the popup from all the 1.19+ clients connecting with viaversion

That will still work with the option I mentioned disabled.

**Comment by TomLewis** [comment]
awesome, thanks! ill give it a try!
